# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addinterestUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from core import connect,insert_into_db



class Ui_AddInterest(object):
    def setupUi(self, AddInterest):
        AddInterest.setObjectName("AddInterest")
        AddInterest.resize(271, 411)
        self.centralwidget = QtWidgets.QWidget(AddInterest)
        self.centralwidget.setObjectName("centralwidget")
        self.QTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.QTextEdit.setGeometry(QtCore.QRect(10, 30, 251, 31))
        self.QTextEdit.setObjectName("QTextEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 101, 16))
        self.label_2.setObjectName("label_2")
        self.QTextEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.QTextEdit_2.setGeometry(QtCore.QRect(10, 90, 251, 191))
        self.QTextEdit_2.setObjectName("QTextEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 300, 251, 51))
        self.pushButton.setObjectName("pushButton")
        AddInterest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddInterest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 271, 21))
        self.menubar.setObjectName("menubar")
        AddInterest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddInterest)
        self.statusbar.setObjectName("statusbar")
        AddInterest.setStatusBar(self.statusbar)

        self.retranslateUi(AddInterest)
        self.pushButton.clicked.connect(lambda:[self.QTextEdit.toPlainText(),insert_into_db('interests','interest',{1:f"'{self.QTextEdit.toPlainText()}'"})])
        # self.pushButton.clicked.connect(self.textBrowser_2.paste)
        QtCore.QMetaObject.connectSlotsByName(AddInterest)

    def retranslateUi(self, AddInterest):
        _translate = QtCore.QCoreApplication.translate
        AddInterest.setWindowTitle(_translate("AddInterest", "MainWindow"))
        self.label.setText(_translate("AddInterest", "Введите Интерес"))
        self.label_2.setText(_translate("AddInterest", "Цели для интереса"))
        self.pushButton.setText(_translate("AddInterest", "Добавить"))
