# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\xxxme\Desktop\Week_Plane\UI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QGridLayout,
                             QPushButton, QApplication,QLabel,)
from datetime import date as dt
from addinterestUI import *
from delinterestUI import *


class addinterestWindow(QtWidgets.QMainWindow):
	def __init__(self):
		super(addinterestWindow, self).__init__()
		self.ui = Ui_AddInterest()
		self.ui.setupUi(self)

app2 = QtWidgets.QApplication([])
application2 = addinterestWindow()

class delinterestWindow(QtWidgets.QMainWindow):
	def __init__(self):
		super(delinterestWindow, self).__init__()
		self.ui = Ui_DelInterest()
		self.ui.setupUi(self)

app3 = QtWidgets.QApplication([])
application3 = delinterestWindow()

class Ui_MainWindow(object):
    def setupUi(self, WeekPlane,secondtable, firtstable, colors):
        self.secondtable = secondtable
        self.firtstable=firtstable
        self.colors=colors
        WeekPlane.setObjectName("WeekPlane")
        WeekPlane.resize(852, 614)
        self.centralwidget = QtWidgets.QWidget(WeekPlane)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 50, 621, 501))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.calendar = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.calendar.setContentsMargins(0, 0, 0, 0)
        self.calendar.setObjectName("calendar")
        calendar=self.calendar
        td = dt.today()
        Monday = QLabel('Понедельник')
        Tuesday = QLabel('Вторник')
        Wednesday = QLabel('Среда')
        Thursday = QLabel('Четверг')
        Friday = QLabel('Пятница')
        Saturday = QLabel('Суббота')
        Sunday = QLabel('Воскресенье')
        positions = [(i, j) for i in range(8) for j in range(8)]
        for position, name in zip(positions, self.secondtable):
            button = QPushButton(name)
            if len(name) == 1:
                continue
            else:
                if td > dt.fromisoformat(name[0:10]): \
                        button.setStyleSheet("background-color: IndianRed")
                else:
                    button.setStyleSheet(f"background-color: {self.colors[name[13:]]}")
            calendar.addWidget(button, *position)
        calendar.addWidget(Monday, 0, 1)
        calendar.addWidget(Tuesday, 0, 2)
        calendar.addWidget(Wednesday, 0, 3)
        calendar.addWidget(Thursday, 0, 4)
        calendar.addWidget(Friday, 0, 5)
        calendar.addWidget(Saturday, 0, 6)
        calendar.addWidget(Sunday, 0, 7)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 0, 581, 31))
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 550, 841, 23))
        self.progressBar.setMaximum(28)
        self.progressBar.setProperty("value", 6)
        self.progressBar.setObjectName("progressBar")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 30, 171, 521))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.Interest_table = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.Interest_table.setContentsMargins(0, 0, 0, 0)
        self.Interest_table.setObjectName("Interest_table")
        label = QLabel(self.firtstable)
        label.setWordWrap(True)
        self.Interest_table.addWidget(label, 0, 0)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, -1, 171, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 30, 80, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(292, 30, 80, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(292+92, 30, 80, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(292+92+90, 30, 80, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(292+92+90+90, 30, 80, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(292+92+90+90+88, 30, 80, 20))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(292+92+90+90+90+84, 30, 80, 20))
        self.label_9.setObjectName("label_9")
        WeekPlane.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(WeekPlane)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 852, 21))
        self.menubar.setObjectName("menubar")
        self.menuvty = QtWidgets.QMenu(self.menubar)
        self.menuvty.setObjectName("menuvty")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        WeekPlane.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(WeekPlane)
        self.statusbar.setObjectName("statusbar")
        WeekPlane.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(WeekPlane)
        self.action.setObjectName("action")
        self.action_3 = QtWidgets.QAction(WeekPlane)
        self.action_3.setCheckable(False)
        self.action_3.setObjectName("action_3")
        self.action_3.triggered.connect(application2.show)
        self.action_5 = QtWidgets.QAction(WeekPlane)
        self.action_5.setObjectName("action_5")
        self.action_5.triggered.connect(application3.show)
        self.menuvty.addAction(self.action)
        self.menuvty.addSeparator()
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_5)
        self.menubar.addAction(self.menuvty.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(WeekPlane)
        QtCore.QMetaObject.connectSlotsByName(WeekPlane)

    def retranslateUi(self, WeekPlane):
        _translate = QtCore.QCoreApplication.translate
        WeekPlane.setWindowTitle(_translate("WeekPlane", "MainWindow"))
        self.label.setText(_translate("WeekPlane",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#00aaff;\">План на {Месяц}</span></p></body></html>"))
        self.label_2.setText(_translate("WeekPlane",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#00aaff;\">Интересы</span></p></body></html>"))
        self.label_3.setText(_translate("WeekPlane", "Понедельник"))
        self.label_4.setText(_translate("WeekPlane", "Вторник"))
        self.label_5.setText(_translate("WeekPlane", "Среда"))
        self.label_6.setText(_translate("WeekPlane", "Четрверг"))
        self.label_7.setText(_translate("WeekPlane", "Пятница"))
        self.label_8.setText(_translate("WeekPlane", "Суббота"))
        self.label_9.setText(_translate("WeekPlane", "Воскресенье"))
        self.menuvty.setTitle(_translate("WeekPlane", "Меню"))
        self.menu.setTitle(_translate("WeekPlane", "Интересы"))
        self.action.setText(_translate("WeekPlane", "Выход"))
        self.action_3.setText(_translate("WeekPlane", "Добавить новый Интерес"))
        self.action_5.setText(_translate("WeekPlane", "Удалить Интерес"))



