# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\xxxme\Desktop\Week_Plane\UI2.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QWidget, QGridLayout,
                             QPushButton, QApplication,QLabel,)
from datetime import date as dt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow,secondtable, firtstable, colors):
        self.secondtable = secondtable
        self.firtstable=firtstable
        self.colors=colors
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 577)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 520, 771, 51))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 1000, 451))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        grid=self.gridLayout
        td = dt.today()
        Monday = QLabel('Понедельник')
        Tuesday = QLabel('Вторник')
        Wednesday = QLabel('Среда')
        Thursday = QLabel('Четверг')
        Friday = QLabel('Пятница')
        Saturday = QLabel('Суббота')
        Sunday = QLabel('Воскресенье')
        positions = [(i, j) for i in range(1, 8) for j in range(8)]
        for position, name in zip(positions, self.secondtable):
            button = QLabel(name)
            if len(name) == 1:
                continue
            else:
                if td > dt.fromisoformat(name[0:10]): \
                        button.setStyleSheet("background-color: grey")
                else:
                    button.setStyleSheet(f"background-color: {self.colors[name[13:]]}")
            grid.addWidget(button, *position)
        label = QLabel(self.firtstable)
        # label.setStyleSheet("background-color: blue");
        grid.addWidget(label, 0, 0, -1, 1)
        grid.addWidget(Monday, 0, 1)
        grid.addWidget(Tuesday, 0, 2)
        grid.addWidget(Wednesday, 0, 3)
        grid.addWidget(Thursday, 0, 4)
        grid.addWidget(Friday, 0, 5)
        grid.addWidget(Saturday, 0, 6)
        grid.addWidget(Sunday, 0, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

